apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-k8s
spec:
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /spring-mongo
