apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-spring-mongo
spec:
   accessModes:
      - ReadWriteOnce
   capacity:
      storage: 10Gi
   persistentVolumeReclaimPolicy: Retain
   nfs:
     server: 192.168.0.60
     path: /mydata